[2022-09-21 00:05:12,832] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: gcs_2_bq_dag.bq_create_yellow_tripdata_partitioned_table_task scheduled__2022-09-20T00:00:00+00:00 [queued]>
[2022-09-21 00:05:12,845] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: gcs_2_bq_dag.bq_create_yellow_tripdata_partitioned_table_task scheduled__2022-09-20T00:00:00+00:00 [queued]>
[2022-09-21 00:05:12,845] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-09-21 00:05:12,845] {taskinstance.py:1239} INFO - Starting attempt 2 of 2
[2022-09-21 00:05:12,845] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-09-21 00:05:12,857] {taskinstance.py:1259} INFO - Executing <Task(BigQueryInsertJobOperator): bq_create_yellow_tripdata_partitioned_table_task> on 2022-09-20 00:00:00+00:00
[2022-09-21 00:05:12,865] {standard_task_runner.py:52} INFO - Started process 23563 to run task
[2022-09-21 00:05:12,870] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'gcs_2_bq_dag', 'bq_create_yellow_tripdata_partitioned_table_task', 'scheduled__2022-09-20T00:00:00+00:00', '--job-id', '202', '--raw', '--subdir', 'DAGS_FOLDER/gcs_to_bq_dag.py', '--cfg-path', '/tmp/tmpvsb0jlt3', '--error-file', '/tmp/tmpbk40qxjt']
[2022-09-21 00:05:12,872] {standard_task_runner.py:77} INFO - Job 202: Subtask bq_create_yellow_tripdata_partitioned_table_task
[2022-09-21 00:05:12,956] {logging_mixin.py:109} INFO - Running <TaskInstance: gcs_2_bq_dag.bq_create_yellow_tripdata_partitioned_table_task scheduled__2022-09-20T00:00:00+00:00 [running]> on host 788dccad41b9
[2022-09-21 00:05:13,041] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=gcs_2_bq_dag
AIRFLOW_CTX_TASK_ID=bq_create_yellow_tripdata_partitioned_table_task
AIRFLOW_CTX_EXECUTION_DATE=2022-09-20T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-20T00:00:00+00:00
[2022-09-21 00:05:13,043] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-09-21 00:05:13,044] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-09-21 00:05:13,052] {bigquery.py:1637} INFO - Inserting job ***_gcs_2_bq_dag_bq_create_yellow_tripdata_partitioned_table_task_2022_09_20T00_00_00_00_00_2578e6aa248b9e2860458a014c1d163a
[2022-09-21 00:05:15,781] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2287, in execute
    job = self._submit_job(hook, job_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2253, in _submit_job
    job_id=job_id,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 430, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1639, in insert_job
    job.result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1447, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1437, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/base.py", line 727, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/future/polling.py", line 135, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Error while reading table: tez_taxi_data.yellow_tripdata_external_table, error message: Parquet column 'airport_fee' has type INT32 which does not match the target cpp_type DOUBLE. File: gs://tez-bucket/yellow/yellow_tripdata/2020/yellow_tripdata_2020-10.parquet

(job ID: airflow_gcs_2_bq_dag_bq_create_yellow_tripdata_partitioned_table_task_2022_09_20T00_00_00_00_00_2578e6aa248b9e2860458a014c1d163a)

                                                                                   -----Query Job SQL Follows-----                                                                                   

    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
   1:CREATE OR REPLACE TABLE tez_taxi_data.yellow_tripdata             PARTITION BY DATE(tpep_pickup_datetime)             AS             SELECT * FROM tez_taxi_data.yellow_tripdata_external_table;
    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
[2022-09-21 00:05:15,804] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=gcs_2_bq_dag, task_id=bq_create_yellow_tripdata_partitioned_table_task, execution_date=20220920T000000, start_date=20220921T000512, end_date=20220921T000515
[2022-09-21 00:05:15,819] {standard_task_runner.py:92} ERROR - Failed to execute job 202 for task bq_create_yellow_tripdata_partitioned_table_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2287, in execute
    job = self._submit_job(hook, job_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2253, in _submit_job
    job_id=job_id,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 430, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1639, in insert_job
    job.result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1447, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1437, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/base.py", line 727, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/future/polling.py", line 135, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Error while reading table: tez_taxi_data.yellow_tripdata_external_table, error message: Parquet column 'airport_fee' has type INT32 which does not match the target cpp_type DOUBLE. File: gs://tez-bucket/yellow/yellow_tripdata/2020/yellow_tripdata_2020-10.parquet

(job ID: airflow_gcs_2_bq_dag_bq_create_yellow_tripdata_partitioned_table_task_2022_09_20T00_00_00_00_00_2578e6aa248b9e2860458a014c1d163a)

                                                                                   -----Query Job SQL Follows-----                                                                                   

    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
   1:CREATE OR REPLACE TABLE tez_taxi_data.yellow_tripdata             PARTITION BY DATE(tpep_pickup_datetime)             AS             SELECT * FROM tez_taxi_data.yellow_tripdata_external_table;
    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
[2022-09-21 00:05:15,854] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-09-21 00:05:15,890] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-09-21 01:42:28,310] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: gcs_2_bq_dag.bq_create_yellow_tripdata_partitioned_table_task scheduled__2022-09-20T00:00:00+00:00 [queued]>
[2022-09-21 01:42:28,328] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: gcs_2_bq_dag.bq_create_yellow_tripdata_partitioned_table_task scheduled__2022-09-20T00:00:00+00:00 [queued]>
[2022-09-21 01:42:28,328] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-09-21 01:42:28,328] {taskinstance.py:1239} INFO - Starting attempt 2 of 2
[2022-09-21 01:42:28,328] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-09-21 01:42:28,347] {taskinstance.py:1259} INFO - Executing <Task(BigQueryInsertJobOperator): bq_create_yellow_tripdata_partitioned_table_task> on 2022-09-20 00:00:00+00:00
[2022-09-21 01:42:28,356] {standard_task_runner.py:52} INFO - Started process 28534 to run task
[2022-09-21 01:42:28,377] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'gcs_2_bq_dag', 'bq_create_yellow_tripdata_partitioned_table_task', 'scheduled__2022-09-20T00:00:00+00:00', '--job-id', '369', '--raw', '--subdir', 'DAGS_FOLDER/gcs_to_bq_dag copy.py', '--cfg-path', '/tmp/tmpnwyaw9j9', '--error-file', '/tmp/tmp0vby1np5']
[2022-09-21 01:42:28,379] {standard_task_runner.py:77} INFO - Job 369: Subtask bq_create_yellow_tripdata_partitioned_table_task
[2022-09-21 01:42:28,491] {logging_mixin.py:109} INFO - Running <TaskInstance: gcs_2_bq_dag.bq_create_yellow_tripdata_partitioned_table_task scheduled__2022-09-20T00:00:00+00:00 [running]> on host 788dccad41b9
[2022-09-21 01:42:28,642] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=gcs_2_bq_dag
AIRFLOW_CTX_TASK_ID=bq_create_yellow_tripdata_partitioned_table_task
AIRFLOW_CTX_EXECUTION_DATE=2022-09-20T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-20T00:00:00+00:00
[2022-09-21 01:42:28,644] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-09-21 01:42:28,645] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-09-21 01:42:28,656] {bigquery.py:1637} INFO - Inserting job ***_gcs_2_bq_dag_bq_create_yellow_tripdata_partitioned_table_task_2022_09_20T00_00_00_00_00_074cd663cc28aa16c17356153e367d8e
[2022-09-21 01:42:29,969] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2287, in execute
    job = self._submit_job(hook, job_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2253, in _submit_job
    job_id=job_id,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 430, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1639, in insert_job
    job.result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1447, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1437, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/base.py", line 727, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/future/polling.py", line 135, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Error while reading table: tez_taxi_data.yellow_tripdata_external_table, error message: Parquet column 'airport_fee' has type INT32 which does not match the target cpp_type DOUBLE. File: gs://tez-bucket/yellow/yellow_tripdata/2020/yellow_tripdata_2020-03.parquet

(job ID: airflow_gcs_2_bq_dag_bq_create_yellow_tripdata_partitioned_table_task_2022_09_20T00_00_00_00_00_074cd663cc28aa16c17356153e367d8e)

                                                                                   -----Query Job SQL Follows-----                                                                                   

    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
   1:CREATE OR REPLACE TABLE tez_taxi_data.yellow_tripdata             PARTITION BY DATE(tpep_pickup_datetime)             AS             SELECT * FROM tez_taxi_data.yellow_tripdata_external_table;
    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
[2022-09-21 01:42:29,990] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=gcs_2_bq_dag, task_id=bq_create_yellow_tripdata_partitioned_table_task, execution_date=20220920T000000, start_date=20220921T014228, end_date=20220921T014229
[2022-09-21 01:42:30,012] {standard_task_runner.py:92} ERROR - Failed to execute job 369 for task bq_create_yellow_tripdata_partitioned_table_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2287, in execute
    job = self._submit_job(hook, job_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2253, in _submit_job
    job_id=job_id,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 430, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1639, in insert_job
    job.result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1447, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1437, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/base.py", line 727, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/future/polling.py", line 135, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Error while reading table: tez_taxi_data.yellow_tripdata_external_table, error message: Parquet column 'airport_fee' has type INT32 which does not match the target cpp_type DOUBLE. File: gs://tez-bucket/yellow/yellow_tripdata/2020/yellow_tripdata_2020-03.parquet

(job ID: airflow_gcs_2_bq_dag_bq_create_yellow_tripdata_partitioned_table_task_2022_09_20T00_00_00_00_00_074cd663cc28aa16c17356153e367d8e)

                                                                                   -----Query Job SQL Follows-----                                                                                   

    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
   1:CREATE OR REPLACE TABLE tez_taxi_data.yellow_tripdata             PARTITION BY DATE(tpep_pickup_datetime)             AS             SELECT * FROM tez_taxi_data.yellow_tripdata_external_table;
    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
[2022-09-21 01:42:30,042] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-09-21 01:42:30,084] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
